### ISSUE TITLE
Inconsistency in `class`

### ISSUE THREAD

**Issue by Rafnuss** [ConservationInternational/Wildlife-Insights----Data-Migration#8]
Is there a difference between `NULL`, `Unknown`, `Other` and `[null]` ? 
![image](https://user-images.githubusercontent.com/7571260/181218065-49299349-dfd4-41dd-8e24-aa263e316aa6.png)

```
Using the R code provided I also have some more inconsistency
wi_taxa <- jsonlite::fromJSON("https://api.wildlifeinsights.org/api/v1/taxonomy?fields=class,order,family,genus,species,authority,taxonomyType,uniqueIdentifier,commonNameEnglish&page[size]=30000")
unique(wi_taxa$data$class)

>  [1] "Mammalia"           "Aves"               "Reptilia"           "Amphibia"          
>  [5] "Arachnida"          NA                   "Gastropoda"         "Malacostraca"      
>  [9] "Clitellata"         "Chilopoda"          "Diplopoda"          "Insecta"           
> [13] "No CV Result"       "CV Needed"          "Salvator rufescens" ""                  
> [17] "CV Failed"          "Other"              "Domestic animal"  
```

`Salvator rufescens` should not be a class, right?

**Comment by VwakeM** [comment]
Hi @Rafnuss - Unknown species is different from NULL. To be used when you know there is an animal in the picture but don't know what species. NULL or NA in the R world just means the absence of values. 

We are standardizing some of these terminologies and inconsistencies that have been crept in to our taxonomy. I have fixed some of the issues you have spotted. 

For any future taxonomy questions/issues/requests, please use this form: https://airtable.com/shrpbVfBPahYkyJmp.
